name: "WeeWX"
description: "WeeWX Home Assistant Add-on"
version: "1.0.0"
slug: "weewx"
init: false
map:
  - type: addon_config
    path: /home/weewx
    read_only: False
  - type: data
    path: /home

ports:
  80/tcp: 8088
  4299/tcp: 4299
ports_description:
  80/tcp: Web Report
  4299/tcp: Interceptor web server
webui: http://[HOST]:[PORT:80]/
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

